# Generated by Django 2.2 on 2019-05-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='城市地点')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20, verbose_name='餐厅名称')),
                ('location', models.CharField(max_length=20, verbose_name='餐厅位置')),
                ('rate', models.IntegerField(verbose_name='评级')),
                ('imgs', models.ImageField(upload_to='hotpic')),
                ('price', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='主题')),
                ('message', models.TextField(verbose_name='内容')),
                ('usuggest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.User', verbose_name='用户外键')),
            ],
        ),
        migrations.CreateModel(
            name='Order_from',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=20, verbose_name='订单类型')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('city_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.City', verbose_name='城市外键')),
                ('rorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.Restaurant', verbose_name='餐厅外键')),
            ],
        ),
    ]
