# Generated by Django 2.2 on 2019-05-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_from',
            name='city_order',
        ),
        migrations.RemoveField(
            model_name='order_from',
            name='rorder',
        ),
    ]
