# Generated by Django 2.2 on 2019-05-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20190510_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='imgs',
            field=models.ImageField(default=None, upload_to='hotpic'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.IntegerField(default=None, verbose_name='评级'),
        ),
    ]
