# Generated by Django 2.2 on 2019-05-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_auto_20190510_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='imgs',
            field=models.ImageField(upload_to='hotpic'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.IntegerField(verbose_name='评级'),
        ),
    ]
