# Generated by Django 2.2 on 2019-05-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_auto_20190510_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='usuggest',
        ),
    ]
